call cd..
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_his_original.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o fs1_original-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod1-p.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod1_p-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod2-e.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod2_e-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod3-s.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod3_s-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod4-pes.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod4_pes-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod5-pe.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod5_pe-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod6-ps.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod6_ps-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS1/ur-fs1_fs-enco_hist_Mod7-es.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-1_Rules_notRuleDuplicate.csv -f ruleValidator-FS1 -o rv-fs1_Mod7_es-expUR2-

call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_his_original.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o fs2_original-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod1-p.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod1_p-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod2-e.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod2_e-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod3-s.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod3_s-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod4-pes.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod4_pes-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod5-pe.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod5_pe-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod6-ps.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod6_ps-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS2/ur-fs2_fs-enco_hist_Mod7-es.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-2_Rules_notRuleDuplicate.csv -f ruleValidator-FS2 -o rv-fs2_Mod7_es-expUR2-

call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_his_original.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o fs3_original-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod1-p.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod1_p-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod2-e.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod2_e-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod3-s.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod3_s-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod4-pes.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod4_pes-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod5-pe.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod5_pe-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod6-ps.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod6_ps-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS3/ur-fs3_fs-enco_hist_Mod7-es.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-3_Rules_notRuleDuplicate.csv -f ruleValidator-FS3 -o rv-fs3_Mod7_es-expUR2-

call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_his_original.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o fs4_original-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod1-p.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod1_p-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod2-e.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod2_e-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod3-s.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod3_s-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod4-pes.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod4_pes-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod5-pe.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod5_pe-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod6-ps.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod6_ps-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS4/ur-fs4_fs-enco_hist_Mod7-es.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-4_Rules_notRuleDuplicate.csv -f ruleValidator-FS4 -o rv-fs4_Mod7_es-expUR2-

call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_his_original.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o fs5_original-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod1-p.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod1_p-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod2-e.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod2_e-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod3-s.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod3_s-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod4-pes.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod4_pes-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod5-pe.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod5_pe-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod6-ps.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod6_ps-expUR2-
call python ruleValidator.py -i uniqueRows/uniqueRows-FS5/ur-fs5_fs-enco_hist_Mod7-es.csv -r Exp-uniqueRows_2/Rules/merged_files/without-duplicates/fs-5_Rules_notRuleDuplicate.csv -f ruleValidator-FS5 -o rv-fs5_Mod7_es-expUR2-